### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by eliizaveta** [radkoff26/flocator#51]
я в тамтам https://tt.me/riinj

Кажется, что можно еще больше обернуть, например сделать метод для ввода текста и закрытия клавиатуры а туда передавать параметры
https://github.com/radkoff26/flocator/blob/775518e90ab175513ba18a8d9058bc5d9b58cca1/app/src/androidTest/java/com/example/flocator/gladyshev_test/pages/RegFirstFragmentPage.kt#L10-L24

Метод для клика тоже можно обернуть, чтобы не писать каждый раз одну и ту же длинную цепочку
https://github.com/radkoff26/flocator/blob/775518e90ab175513ba18a8d9058bc5d9b58cca1/app/src/androidTest/java/com/example/flocator/gladyshev_test/pages/RegFirstFragmentPage.kt#L27

Хочется добавить паттерн лоадабл компонент

Скрыть в пейджах, ожидаемый текст в константы
https://github.com/radkoff26/flocator/blob/775518e90ab175513ba18a8d9058bc5d9b58cca1/app/src/androidTest/java/com/example/flocator/gladyshev_test/RegFirstFragmentTest.kt#L35-L36

Можно сделать цепочку вызовов
https://github.com/radkoff26/flocator/blob/775518e90ab175513ba18a8d9058bc5d9b58cca1/app/src/androidTest/java/com/example/flocator/gladyshev_test/RegFirstFragmentTest.kt#L44-L46

Всякие Espresso., ViewActions. и тд усложняют прочтение кода, можно сделать так, чтобы это было в импортах, а не тут
https://github.com/radkoff26/flocator/blob/775518e90ab175513ba18a8d9058bc5d9b58cca1/app/src/androidTest/java/com/example/flocator/radko_test/fragments/TestAuthFragment.kt#L12

Возможно слишком много действий для одной функции
https://github.com/radkoff26/flocator/blob/775518e90ab175513ba18a8d9058bc5d9b58cca1/app/src/androidTest/java/com/example/flocator/radko_test/fragments/TestAuthFragment.kt#L11-L20

Можно вынести в базовый тестовый класс
https://github.com/radkoff26/flocator/blob/775518e90ab175513ba18a8d9058bc5d9b58cca1/app/src/androidTest/java/com/example/flocator/radko_test/tests/AuthFragmentTest.kt#L26-L30

**Comment by Alexander-1703** [comment]
Исправил: https://github.com/radkoff26/flocator/pull/58
Гладышев
